### ISSUE TITLE
某些字体解析错误

### ISSUE THREAD

**Issue by sbfkcel** [ecomfe/fonteditor#17]
一些otf字体解析出错~~~

如图：
![snipaste20170905_094747](https://user-images.githubusercontent.com/5469785/30041795-8d866a32-921f-11e7-9765-7736e6b7d18d.png)

字体名称：SourceHanSansCN 
格式：otf

**Comment by kekee000** [comment]
是有一些otf指令解析有问题，排查过一次，使用了一些不是文档里的指令，有时间修复
