### ISSUE TITLE
文件稍大（2M）就下载失败

### ISSUE THREAD

**Issue by wen911119** [ecomfe/fonteditor#19]
实测，一两个字是可以下载的，但是导入一个1.75M的字体文件，然后编辑了下，就百分百下载失败了
求解决啊！真的很好用！

**Comment by kekee000** [comment]
你好，在线编辑器受限于浏览器脚本运行时间，是有导出限制的，大字体文件确实处理有问题，建议使用 FontCreator等工具编辑。
如果只用来处理 web iconfont 是够用了。
