### ISSUE TITLE
导出的 svg 图像不垂直居中

### ISSUE THREAD

**Issue by 100pah** [ecomfe/fonteditor#20]
有些图标不是正方形的，导出的 svg，默认 viewBox="0 0 1024 1024" ，从而图像不能垂直居中。如图：

![image](https://user-images.githubusercontent.com/1956569/35852119-faed6f30-0b64-11e8-94ed-659ade00e86c.png)

**Comment by kekee000** [comment]
默认的导出功能不支持调整生成，可以先下载svg，使用fonteditor，新建字体后，拽进去，编辑后导出字形：

![image](https://user-images.githubusercontent.com/3490015/36071547-91371e6c-0f4a-11e8-97ec-3ac9c4fcef11.png)
