### ISSUE TITLE
有效字体个数如果单数, 导出的字体是倒立的.

### ISSUE THREAD

**Issue by chuanxinwong** [ecomfe/fonteditor#22]
如图  http://wx2.sinaimg.cn/mw690/0060lm7Tly1fwsdljtcqpj30gm0epq39.jpg

导出的时候加了一个循环 循环导出10份, 总会有一半 字是倒立的

**Comment by kekee000** [comment]
这个应该是一个已知的bug，最好拷贝一份对象导出，或者保存一次之后再打开导出，当前没有修复。
