### ISSUE TITLE
导入时代码点重复问题

### ISSUE THREAD

**Issue by sniperwrb** [ecomfe/fonteditor#25]
是否考虑提供一个设置：
代码点重复时无视
或者
代码点重复时覆盖？
而不是保留两种字体，导致代码点重复，无法导出。（中文+日文字体，几千个码位重复，手动删不太可能啊，自动删只能删第一页……）

**Comment by kekee000** [comment]
这个编辑器编辑几千个码位还是很吃力，建议用专业的编辑器配置
