### ISSUE TITLE
无法设置空格字符的rightSideBearing

### ISSUE THREAD

**Issue by ppnman** [ecomfe/fonteditor#27]
仅有空格字符有这个问题！
拖动了rightSideBearing之后，点击保存，再次进来发现并没有改动。

**Comment by kekee000** [comment]
空格字符没有字形，计算不出来rightSideBearing

**Comment by ppnman** [comment]
> 空格字符没有字形，计算不出来rightSideBearing

那请问如何设置空格字符的占用空间呢？
一般我都是拖动rightSideBearing来设置一个字符的占用空间。
