### ISSUE TITLE
线上版本出问题了

### ISSUE THREAD

**Issue by LiuQuanXin** [ecomfe/fonteditor#33]
添加woff文件进去的时候出现「e.inflate is not a function」错误

**Comment by liuxilu** [comment]
看你说的，还以为是服务器挂了……

**Comment by dreamzyh** [comment]
可以用http://blog.luckly-mjw.cn/tool-show/iconfont-preview/index.html

**Comment by kekee000** [comment]
请提供出问题的woff文件地址，我追查一下

**Comment by LiuQuanXin** [comment]
woff文件附件


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"kekee000"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月6日(星期三) 上午10:57
收件人:&nbsp;"ecomfe/fonteditor"<fonteditor@noreply.github.com&gt;;
抄送:&nbsp;"刘泉鑫"<3137911394@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ecomfe/fonteditor] 线上版本出问题了 (#33)




请提供出问题的woff文件地址，我追查一下

**Comment by kekee000** [comment]
fixed请使用这个地址编辑：
https://kekee000.github.io/fonteditor/index.html
