### ISSUE TITLE
安装不成功是什么问题？

### ISSUE THREAD

**Issue by ch3ngxuyuan** [ecomfe/fonteditor#40]
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\WebSite\
PHP\www\iconfont\fonteditor-master\node_modules\fsevents\node_modules\inherits' -> 'E:\WebSite\PHP\w
ww\iconfont\fonteditor-master\node_modules\fsevents\node_modules\.inherits.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ini@1.3.5 (node_modules\fsevents\node_modules\ini):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\WebSite\
PHP\www\iconfont\fonteditor-master\node_modules\fsevents\node_modules\ini' -> 'E:\WebSite\PHP\www\ic
onfont\fonteditor-master\node_modules\fsevents\node_modules\.ini.DELETE'...
...
ERROR in ./src/fonteditor/template/export/icon-css.tpl 5:0
Module parse failed: Unexpected character '@' (5:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to
process this file. See https://webpack.js.org/concepts#loaders
|  */
|
> @font-face {
|     font-family: "{%=fontFamily%}";
|     src: url("{%=fontFamily%}.eot"); /* IE9 */
 @ ./src/fonteditor/template/export-render.js 43:55-87
 @ ./src/fonteditor/widget/exporter.js
 @ ./src/fonteditor/index.js
...
ERROR in Template execution failed: ReferenceError: lang is not defined

ERROR in   ReferenceError: lang is not defined

  - index.tpl:100
    E:/WebSite/PHP/www/iconfont/fonteditor-master/index.tpl:100:10

**Comment by kekee000** [comment]
安装还是启动不成功，使用的webpack4

**Comment by GKennyKwok** [comment]
我也遇到这个问题了，master，ver2两个分支都不行，

**Comment by GKennyKwok** [comment]
我也遇到这个问题了，master，ver2两个分支都不行，
`
ERROR in ./src/fonteditor/template/export/icon-css.tpl 5:0
Module parse failed: Unexpected character '@' (5:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| */
|

@font-face {
| font-family: "{%=fontFamily%}";
| src: url("{%=fontFamily%}.eot"); /* IE9 */
@ ./src/fonteditor/template/export-render.js 43:55-87
@ ./src/fonteditor/widget/exporter.js
@ ./src/fonteditor/index.js

ERROR in ./src/fonteditor/template/dialog/setting-sync.tpl 2:0
Module parse failed: Unexpected token (2:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|

| ${lang.cancelsync}
|


@ ./src/fonteditor/dialog/setting-sync.js 14:15-61
@ ./src/fonteditor/dialog/support.js
@ ./src/fonteditor/widget/GLYFEditor.js
@ ./src/fonteditor/index.js
ERROR in Template execution failed: ReferenceError: lang is not defined

ERROR in ReferenceError: lang is not defined

index.tpl:100
E:/GitHub/fonteditor/index.tpl💯10

index.tpl:197 ./node_modules/html-webpack-plugin/lib/loader.js!./index.tpl?en-us.module.exports
E:/GitHub/fonteditor/index.tpl:197:3

index.js:284
[fonteditor]/[html-webpack-plugin]/index.js:284:18

task_queues.js:94 processTicksAndRejections
internal/process/task_queues.js:94:5`


上面是主要的3个报错
npm start, npm run prod 都不行
我是win10 下 使用vscode编译

**Comment by aolsx** [comment]
+1

**Comment by jerryyan1990** [comment]
> 我也遇到这个问题了，master，ver2两个分支都不行，
> `
> ERROR in ./src/fonteditor/template/export/icon-css.tpl 5:0
> Module parse failed: Unexpected character '@' (5:0)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> | */
> |
> 
> @font-face {
> | font-family: "{%=fontFamily%}";
> | src: url("{%=fontFamily%}.eot"); /* IE9 */
> @ ./src/fonteditor/template/export-render.js 43:55-87
> @ ./src/fonteditor/widget/exporter.js
> @ ./src/fonteditor/index.js
> 
> ERROR in ./src/fonteditor/template/dialog/setting-sync.tpl 2:0
> Module parse failed: Unexpected token (2:0)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> |
> 
> | ${lang.cancelsync}
> |
> 
> @ ./src/fonteditor/dialog/setting-sync.js 14:15-61
> @ ./src/fonteditor/dialog/support.js
> @ ./src/fonteditor/widget/GLYFEditor.js
> @ ./src/fonteditor/index.js
> ERROR in Template execution failed: ReferenceError: lang is not defined
> 
> ERROR in ReferenceError: lang is not defined
> 
> index.tpl:100
> E:/GitHub/fonteditor/index.tpl💯10
> 
> index.tpl:197 ./node_modules/html-webpack-plugin/lib/loader.js!./index.tpl?en-us.module.exports
> E:/GitHub/fonteditor/index.tpl:197:3
> 
> index.js:284
> [fonteditor]/[html-webpack-plugin]/index.js:284:18
> 
> task_queues.js:94 processTicksAndRejections
> internal/process/task_queues.js:94:5`
> 
> 上面是主要的3个报错
> npm start, npm run prod 都不行
> 我是win10 下 使用vscode编译

我也是一样的问题( •̀ ω •́ )y

**Comment by jerryyan1990** [comment]
+1 有人知道怎么回事吗？

**Comment by jerryyan1990** [comment]
+1 同样的问题 @kekee000

**Comment by jerryyan1990** [comment]
windows系统，需要修改webpack配置中的rules正则表达式
```
{
        test: /\\(index|empty|editor)\.tpl$/,
        loader: "index-loader",
      },
      {
        test: /template\\(.+?)\.tpl$/,
        loader: "tpl-loader",
      },
```

**Comment by ch3ngxuyuan** [comment]
> 安装还是启动不成功，使用的webpack4

启动不成功，提示：
ERROR in Template execution failed: ReferenceError: lang is not defined
ERROR in   ReferenceError: lang is not defined

**Comment by ch3ngxuyuan** [comment]
> windows系统，需要修改webpack配置中的rules正则表达式
> 
> ```
> {
>         test: /\\(index|empty|editor)\.tpl$/,
>         loader: "index-loader",
>       },
>       {
>         test: /template\\(.+?)\.tpl$/,
>         loader: "tpl-loader",
>       },
> ```

谢谢，照你这个方法修改成功了!
