### ISSUE TITLE
导入图片新加的字，如何使用输入法输出

### ISSUE THREAD

**Issue by kaiji95** [ecomfe/fonteditor#49]
![image](https://user-images.githubusercontent.com/12639372/138590192-15be72d6-fcce-458e-91dc-bd6835394f20.png)
![image](https://user-images.githubusercontent.com/12639372/138590194-f20cce76-8051-4620-a792-42ec3d4c29a3.png)

**Comment by cndpi** [comment]
看你上面的字是正常的CJK区一般输入法直接输入就可以（支持几好万字）。还用一个方法通过unicode转换或是unicode输入法，如果是私用区那肯定得用它。

**Comment by kaiji95** [comment]
@cndpi 使用unicode 转换确实可以，谢谢

**Comment by cndpi** [comment]
加Q或是微信同号：5878735，多交流。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ecomfe/fonteditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月26日(星期五) 上午9:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ecomfe/fonteditor] 导入图片新加的字，如何使用输入法输出 (#49)





 
@cndpi 使用unicode 转换确实可以，谢谢
