### ISSUE TITLE
Android browser missing icon

### ISSUE THREAD

**Issue by Linrstudio** [ecomfe/fonteditor#5]
生成的 ttf 字体，很多安卓版本浏览器，部分字符不显示（如红米）

**Comment by junmer** [comment]
多谢反馈，请问具体是哪个版本呢 系统 x.x ?  红米 哪个型号？
方便的话 可否提供一下 ttf 文件？谢谢

**Comment by Linrstudio** [comment]
起初我是使用 svg2ttf 这个库生成的 ttf 字体，有字符不显示，后来使用 fonteditor 也试了一下，也有一个字符不显示。ttf 我测试不行，就删除了，有空了我再用 fonteditor 生成一个试试。svg2ttf  生成的还有  http://qrobot.qq.com/html5test/webfont/ Android browser missing icon "小“ 字不见了

**Comment by Linrstudio** [comment]
使用 fonteditor 生成了一下，http://qrobot.qq.com/html5test/webfont10/   \e003  不显示，麻烦看一下。

**Comment by kekee000** [comment]
我看了下woff压缩格式字体在android4.x版本系统中uc、百度浏览器、qq浏览器不显示，非压缩格式可以显示，ttf格式显示没问题。
使用时应同时提供woff和ttf格式的font-face，以便于不支持woff的浏览器可以使用ttf字体。
fonteditor对有些svg指令转换有问题，方便的话请提供svg格式文件，我进行一下修正。

**Comment by Linrstudio** [comment]
@kekee000  怎么发给你呢？

**Comment by kekee000** [comment]
发送到我的邮箱就好了，多谢哈

**Comment by Linrstudio** [comment]
已发，谢谢！

**Comment by kekee000** [comment]
已经修复svg导入变形问题，svg文件最好通过adobe illustrator转换成路径再导入，以减少错误。
woff格式已经改成非压缩，部分安卓浏览器woff显示有问题，暂时没有找到原因，已新增同步字体功能，方便开发使用。
预览版地址：
http://mkwiser.sinaapp.com/fonteditor/index.html
