### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by guangting** [ecomfe/fonteditor#53]
可以说下编译环境吗，谢谢

**Comment by kekee000** [comment]
麻烦贴一下编译报错，在 Mac Node 16 环境下没问题。

- npm run dev 启动开发
- npm run build 构建

**Comment by guangting** [comment]
![image](https://user-images.githubusercontent.com/4426045/226786311-3f5ca0a5-1150-4b0f-88ff-52f0cb6a5101.png)
![image](https://user-images.githubusercontent.com/4426045/226786343-333ea97c-41d8-4a44-85c7-c7b2ff2e315c.png)
环境是windows    node 16.15.1
我感觉是loader的问题

**Comment by baekilda** [comment]
如果遇到错误
```
ERR_OSSL_EVP_UNSUPPORTED
```
可以这样解决：
```
export NODE_OPTIONS=--openssl-legacy-provider
npm run build
```
