### ISSUE TITLE
有办法根据一个字形的unicode号知道它代码的汉字吗

### ISSUE THREAD

**Issue by jackluson** [ecomfe/fonteditor#55]
比如下面这个“王”字，我知道它的unicode号为46f0,但其实我不知道它真实汉字，因为显示是svg图形绘制的
<img width="134" alt="image" src="https://github.com/ecomfe/fonteditor/assets/36684351/36b8fce7-5d34-44f6-90b6-1bdcdf62f5a4">

**Comment by kekee000** [comment]
可以自由转换的：
```javascript
'王'.codePointAt(0).toString(16)
王 = '\u738b'
```
