### ISSUE TITLE
怎么将字体的中文和另一个字体的英文、数字合并？

### ISSUE THREAD

**Issue by Suz1e** [ecomfe/fonteditor#56]

**Comment by kekee000** [comment]
建议用专业版的 字体编辑器，例如 fontcreator 或者 fontlab，在线版编辑器不支持大字体文件合并

**Comment by lxgw** [comment]
或许可以试试[魔兽字体合并补全工具](https://github.com/nowar-fonts/Warcraft-Font-Merger)。
