### ISSUE TITLE
SVG_FONT_ID as option

### ISSUE THREAD

**Issue by yckart** [ecomfe/fonteditor#6]
I really want to get control about `SVG_FONT_ID`-var in https://github.com/ecomfe/fonteditor/blob/babc9d9aba1a18f0158a123113575a47deaadb5d/src/ttf/ttf2svg.js#L20

**Comment by junmer** [comment]
hi, this issue has been fixed
you can control `SVG_FONT_ID` here
![image](https://cloud.githubusercontent.com/assets/3205092/7082468/6fda2ee4-df87-11e4-84c2-b257dff2e549.png)
![image](https://cloud.githubusercontent.com/assets/3205092/7082470/7fdfe1d0-df87-11e4-9489-9af4158bf982.png)

thanks
